project_id = "evals-webapp"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://evals-webapp.vercel.app"
additional_redirect_urls = [
  "http://localhost:8080/auth/callback",
  "https://evals-webapp.vercel.app/auth/callback",
]

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_OAUTH_CLIENT_ID)"
secret = "env(GOOGLE_OAUTH_CLIENT_SECRET)"

[storage]
enabled = true

[functions.generate-export]
verify_jwt = true
